# -*- coding: utf-8 -*-
"""Pro5Contactbook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tl2HNI5Uvv2gQ_bRVg-24j1J6w_VGYs2
"""

# Commented out IPython magic to ensure Python compatibility.
# %%markdown
# #. **Pro5 Contact-Book**
# ##_Student name: Kishwar Saleem Khan_
# ##This Project Add And Searches Using A Dictionary.

contact={}
print("Contact dictionary is ready.")

#empty dictionary for contact
contact = {}
print("======CONTACT BOOK=====")

while True:
  print("\n1. Add contact\n2. Search contact\n3. Exit")
  choice = input("Enter your choice: ").strip()

  if choice == "1":
    name = input("Enter contact name: ").strip().title()
    phone = input("Enter phone number: ").strip()
    email = input("Enter email address: ").strip()

    if name == "" or phone == "" or email == "":
      print("All information is required.")
    else:
      contact[name] = {
          "phone": phone,
          "email": email
      }
      print("Contact added successfully.")

  elif choice == "2":
    search_name = input("Enter name to search: ").strip().title()
    if search_name in contact:
      print(f"Name: {search_name}")
      print(f"Phone: {contact[search_name]['phone']}")
      print("Email:", contact[search_name]["email"])
    else:
      print("Contact not found.")

  elif choice == "3":
    print("Contact book close")
    break

  else:
    print("Invalid choice. Please try again.")